### PR TITLE
Multi-cluster collectives

### PR DESCRIPTION
**Pull request by pavanbalaji**
This PR provides an initial code draft for multi-cluster collectives.  It provides a new team that wraps around UCX and NCCL teams and allows them to be used in a hierarchical fashion.

It also imports the "uthash" library.  I wonder if that is acceptable or if a different hash library is preferred.

### CODE REVIEW

**Comment by pavanbalaji** [comment]
Sorry, something seems to have gone wrong in my code import.  I'm looking into it.

**Comment by Sergei-Lebedev** [comment]
> Sorry, something seems to have gone wrong in my code import. I'm looking into it.

Looks like hierarchical team tries to use it, if it is not expected behavior then you need to disable TL_MPOD in hier team

**Comment by pavanbalaji** [comment]
Fixed the build issue.  Also took the opportunity to rebase on to the latest master.

**Comment by pavanbalaji** [comment]
Any comments on this PR?

**Comment by bureddy** [comment]
@pavanbalaji overall it looks fine. 
it is acceptable here as XCCL is an experimental codebase and it is going to replace with UCC.
It needs a broader community acceptance when you port this into UCC. You are welcome to bring this PR into one of the UCC's weekly meetings (https://github.com/openucx/ucc/wiki/UCF-Collectives-Working-Group) and discuss it there.

**Comment by pavanbalaji** [comment]
> @pavanbalaji overall it looks fine.
> it is acceptable here as XCCL is an experimental codebase and it is going to replace with UCC.
> It needs a broader community acceptance when you port this into UCC. You are welcome to bring this PR into one of the UCC's weekly meetings (https://github.com/openucx/ucc/wiki/UCF-Collectives-Working-Group) and discuss it there.

Thank you, @bureddy.  For now, I think it's good to get it into XCCL first.  If it's acceptable, can it be merged in?

**Comment by bureddy** [comment]
@pavanbalaji do you want this in the master branch (or) torch branch?  
I think Pallab/Srinivas is using "torch" branch for FB POCs.

**Comment by pavanbalaji** [comment]
Hi @bureddy: I was planning to do it in both.  Once it gets into master, I was planning to submit another PR for the torch branch.

**Comment by pavanbalaji** [comment]
Hi @bureddy: Any more comments on this or is this ready to be merged?

**Review by bureddy — APPROVED** [review]

**Pull request merged**
